plugins {
    id 'fabric-loom' version '1.5-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url "https://maven.fabricmc.net/" }
    // Add the snapshot repository to resolve the permissions API
    maven { url "https://repo.lucko.me/" }
    mavenCentral()
}

dependencies {
        minecraft "com.mojang:minecraft:1.20.1"
        mappings "net.fabricmc:yarn:1.20.1+build.10:v2"

        modImplementation "net.fabricmc:fabric-loader:0.15.11"
        modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.2+1.20.1"

        compileOnly "net.luckperms:api:5.4"
}

loom {
    runs {
        client {
            client()
            ideConfigGenerated true
        }

        server {
            server()
            ideConfigGenerated true
        }
    }
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}